dist: xenial
language: cpp

install:
  - sudo apt-get install scons
  - pip install colorama grip jinja2 lxml.html --user

script:
  - cd SimpleAPI
  - git clone https://github.com/ja11sop/cuppa.git site_scons
  - scons
