Import('env')

env.Build('Main1', ['Main1.cpp', 'SimpleAPI.cpp', 'Utils.cpp'])
env.Build('Main2', ['Main2.cpp', 'SimpleAPI.cpp', 'Wrapper.cpp', 'Utils.cpp'])
env.Build('Main3', ['Main3.cpp', 'SimpleAPI.cpp', 'Wrapper.cpp', 'Utils.cpp'])
env.Build('Main4', ['Main4.cpp', 'SimpleAPI.cpp', 'Wrapper.cpp', 'Utils.cpp'])
env.Build('Main5', ['Main5.cpp', 'SimpleAPI.cpp', 'Wrapper.cpp', 'Utils.cpp'])
