Import('env')

env.BuildTest('Main1', ['Main1.cpp', 'SimpleAPI.cpp', 'Utils.cpp'])
env.BuildTest('Main2', ['Main2.cpp', 'SimpleAPI.cpp', 'Wrapper.cpp', 'Utils.cpp'])
env.BuildTest('Main3', ['Main3.cpp', 'SimpleAPI.cpp', 'Wrapper.cpp', 'Utils.cpp'])
env.BuildTest('Main4', ['Main4.cpp', 'SimpleAPI.cpp', 'Wrapper.cpp', 'Utils.cpp'])
env.BuildTest('Main5', ['Main5.cpp', 'SimpleAPI.cpp', 'Wrapper.cpp', 'Utils.cpp'])
