# SConstruct for use with cuppa
import os
import cuppa
    
class log4cpp( cuppa.profile( 'log4cpp' ) ):
  def __call__( self, env, toolchain, variant ):
    LOG4CPP_HOME = os.getenv('LOG4CPP_HOME', '/usr/local');
    env.AppendUnique( SYSINCPATH = [os.path.join(LOG4CPP_HOME, 'include')] )
    env.AppendUnique( LIBPATH    = [os.path.join(LOG4CPP_HOME, 'lib')] )
    env.AppendUnique( STATICLIBS = ['log4cpp'] )

# Call sconscripts to do the work
cuppa.run(
  default_options = {
    'parallel': True,
  },
  default_profiles = [
    log4cpp,
  ],
  default_variants = [
    'dbg',
  ],
)
