# SConstruct for use with cuppa
import os

try:
  import cuppa
except ImportError:
  print "Cuppa not found, installing..."
  import subprocess, shlex
  subprocess.call( shlex.split( 'pip install cuppa -t .' ) )
  import cuppa


# Call sconscripts to do the work
cuppa.run(
  default_options = {
    'parallel': True,
  },
  default_dependencies = [
    cuppa.location_dependency('spdlog', location="git+https://github.com/gabime/spdlog.git@v1.3.1", sys_include='include')
  ],
  default_variants = [
    'dbg',
  ],
)
